CREATE TABLE users (
        US_ID INT AUTO_INCREMENT PRIMARY KEY,
        US_NOME VARCHAR(100) NOT NULL,
        US_CPF VARCHAR(14) UNIQUE NOT NULL,
        US_EMAIL VARCHAR(100) NOT NULL,
        US_SENHA VARCHAR(10) NOT NULL,
        US_DATA_NASCIMENTO DATA,
    );

    CREATE TABLE vacinas (
        VC_ID INT AUTO_INCREMENT PRIMARY KEY,
        VC_NOME VARCHAR(100) NOT NULL,
        VC_DESCRICAO TEXT,
        VC_FAIXA_ETARIA_MINIMA INT,
        VC_FAIXA_ETARIA_MAXIMA INT,
        VC_INTER_REFORCO INT,
        VC_FAB VARCHAR(100) NOT NULL,
        VC_CONTRA_INDICACAO TEXT
    )

    CREATE TABLE postos (
        PS_ID INT AUTO_INCREMENT PRIMARY KEY,
        PS_NOME VARCHAR(100) NOT NULL,
        PS_ENDERECO TEXT,
        PS_TELEFONE VARCHAR(45),
    )

    CREATE TABLE historico_vacinas (
        HVC_ID INT AUTO_INCREMENT PRIMARY KEY,
        US_ID INT,
        VC_ID INT,
        HVC_DATA_APLICACAO DATE,
        HVC_DATA_REFORCO DATE,
        PS_ID INT,
        FOREIGN KEY (US_ID) REFERENCES users(US_ID),
        FOREIGN KEY (VC_ID) REFERENCES vacinas(VC_ID),
        FOREIGN KEY (PS_ID) REFERENCES postos(PS_ID),
    )